#
# Feature flags - Begin
#

# Replace this placeholder with the feature flags

#
# Feature flags - End
#

# jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
# jdbc.default.url=jdbc:mysql://testathon-database:3310/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
# jdbc.default.username=root
# jdbc.default.password=

passwords.default.policy.change.required=false
setup.wizard.enabled=false
terms.of.use.required=false
users.reminder.queries.enabled=false